### PR TITLE
Pb pulse charge mod 

### PR DESCRIPTION
**Pull request by Djok39**

### CODE REVIEW

**Comment by stawel** [comment]
a very useful command:
git rebase -i
this allows you to merge many different "commits" into one.

**Comment by jarno83** [comment]
Hi, is the pb pulse charging strategy working? Thanks

**Comment by Djok39** [comment]
Re: [cheali-charger] Pb pulse charge mod  (#98)



Hi, it working, but not in best way (voltage changing too slowly, may damage battery, if set high current for already charged battery).





Hi, is the pb pulse charging strategy working? Thanks

**Comment by Djok39** [comment]
use this branch https://github.com/Djok39/cheali-charger/tree/Branch_016cae66394b9023b2407ba38251d10c2590a1a4

**Comment by jarno83** [comment]
Hi, yes I compiled from that branch. I used old and bad 6ah battery for testing(don't want do hurt my new one:) )
Here are some pics from logview:

logview-pb_pulses

What I noticed was, that on pulse charging the voltage & current decreased and not the opposite.
Maybe it's my bad battery.

May I ask, what do these settings do: PulsePeriod and Pulse duty?
Is it doable to add battery maintenance mode ( stage 3 ) to the strategy so the charger can be connected to battery for long period and charge a bit when needed when not ridding my motorcycle.
 
Thanks,
Jarno

**Comment by Djok39** [comment]
> May I ask, what do these settings do: PulsePeriod and Pulse duty?
Pulse period - time for full cycle (charge + pause) in seconds, duty - is time in percent for charging. (if duty 33% and period 3 - that mean 1 second for pulse and 2 for waiting)
But considering that the discrete time setting - 1 second. ie for greater predictability / accuracy should be selected settings so that the period of the charge or pause amounted integer number of seconds (maybe even better - more than 2 to more accurately measure the voltage)

About stage 3 - i did not thinked about it, can't say that i will do this:)

Your battery looks wery bad, can you set up it for discharge/charge cycle(s) to view benefis from desulfating? (charging current may be high, if battery not overheating)
but looks like, this battery have short circuit and not looks to be working :(
It is not AGM?

**Comment by Djok39** [comment]
i tested this method on my dead AGM batteryes and i can't say, that they can go back from dead :8ball:

**Comment by jarno83** [comment]
It was a dead amg (killed by imax b6 fake firmware, because voltage was to high for amg with small amp(6ah) 25 celsius and more than 14.5v and some my mistakes also(2amp charging current). info I found - 
https://dl.dropboxusercontent.com/u/54767697/Screenshot%20from%202013-12-29%2006%3A07%3A11.png), I used that old battery just for testing ;)

My car battery also need's charging maybe I test with that?

I'm a newbie when it comes to programming c/c++, so... what do we need do to for getting maintenance function to work? Do we great a new strategy for that or mod pulse charging one?

Thanks,
Jarno

**Comment by Djok39** [comment]
I think you need to modify the behavior after the charging process, but only for Pb batteries. voltage monitoring must continue to work, and when the voltage falls below a certain value (12.6 ... 13.2) should be re-run, selected in settings, charge strategy (pulse strategy is not ready yet, so then CCCV)
Stawel's opinion is also important.

You can try a car battery - it must be hard to kill by current of 5 amps ... but I have not tried: D

**Comment by Djok39** [comment]
btw, it may be hard to fit that much code in standart flash...

**Pull request closed without merging**
