### PR TITLE
Can you write more new function

### PR DESCRIPTION
**Pull request by chung1608**
Can you write more function make imax B6 become a power supply can adjust current and voltage output

### CODE REVIEW

**Comment by chung1608** [comment]
Can you guide me how to compile the code to hex file plz. I just know arduino so this open source I dont know.

**Comment by stawel** [comment]
please see https://github.com/stawel/cheali-charger/blob/master/docs/building.md

**Comment by MRC3742** [comment]
@stawel 
When building firmware target from the develop branch.
The Settings Menu contains two identical options for the Fan settings.
It appears it was added in the above commit d8d63dc

There is a duplicate line in SettingsMenu.cpp (develop branch)
https://github.com/stawel/cheali-charger/blob/fc3b40bedb19874ad5da0497c8a9d971bf8d4183/src/core/menus/SettingsMenu.cpp#L113
https://github.com/stawel/cheali-charger/blob/fc3b40bedb19874ad5da0497c8a9d971bf8d4183/src/core/menus/SettingsMenu.cpp#L120
Should one of these be removed? Line 120?

Thanks - Rich

**Comment by diggit** [comment]
Closing this PR, as nothing is happening here. There is several issues opened regarding PSU feature.

**Pull request closed without merging**
