### PR TITLE
docfix

### PR DESCRIPTION
**Pull request by specing**
docs: switch :r to :i in order to produce .hex files in intel hex format.

Maybe add an SHA* checksum as well?

### CODE REVIEW

**Comment by stawel** [comment]
Thanks for the patch!
would you consider to change it and leave only one line, the one with .hex:i?
(the other one is probably redundant)

> Maybe add an SHA* checksum as well?

You could give more details?

**Comment by specing** [comment]
The reason there are two lines is to continue the tradition of all the pre-compiled binaries in hex/ being provided in both intel hex and binary formats. The same goes for adding checksums, all the binaries in hex/ have an accompanying .sha1 (which is unnecessary given that git itself already checksums commits and their contents). It was in question form instead of a command simply because I do not know how to do this on Windows. On most *NIX it would be just shasum flash.bin > flash.sha1.

Speaking of those provided binaries, have you considered making a seperate repo for them and submoduling this repo? Those files are probably the reason why the repo clocks in at 120MB on my harddrive.

**Comment by specing** [comment]
Another thing I noticed: reading out original IMAX B6 atmega firmware resulted in files full of 
:2000000000000101020203030404050506060707080809090A0A0B0B0C0C0D0D0E0E0F0FF0
and so forth (note the rising pattern). I take it is flash readout protection, but had not found any mention in the atmega32 datasheet about this pattern.

**Comment by stawel** [comment]
> Speaking of those provided binaries, have you considered making a seperate repo for them and submoduling this repo? Those files are probably the reason why the repo clocks in at 120MB on my harddrive.

you, I was thinking about it (there is somewhere even a release "place" in github), but
all my scripts are currently working with the /hex/ directory and I don't have the free time to
further work on this project, unfortunately..

> I take it is flash readout protection, but had not found any mention in the atmega32 datasheet about this pattern.

yes, this patter means you charger is protected.

**Comment by specing** [comment]
No problem, repo fix can be done at some other time by cherry-picking hex-update commits and moving them to a different repo, then making a submodule update commit in their place. This can be scripted. Or there can be "see XYZ repo for precompiled binaries" in docs without any submodules.
At the same time those commits would be cherry-picked out of main repo and the update force-pushed. This would be a bit of an inconvenience as everyone would have to git pull --force once and then it would be business as usual (with repo size - 100MB).

I see

**Pull request merged**
